### ISSUE TITLE
Report duplicate identifiers in arrays

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#48]
Issue present in draft data shared by a publisher but not reported in the DRT.

**Comment by Bjwebb** [comment]
Similar to https://github.com/open-contracting/cove-oc4ids/issues/49#issuecomment-663627631 should this be done by schema validation?

**Comment by jpmckinney** [comment]
I think #49 is about entire objects in arrays being equal, whereas this issue is about two objects having the same `id` value (if present).

**Comment by Bjwebb** [comment]
Cove checks whether `id`s are the same, before it does full array comparisons, in order to speed up the checking and to impose the additional constraint that `ids`s should not be equal. We do this by overwriting the relevant jsonschema validator function https://github.com/OpenDataServices/lib-cove/blob/master/libcove/lib/common.py#L59

**Comment by duncandewhurst** [comment]
Since `uniqueItems` was added to all arrays in 0.9.2 this is now covered by the existing CoVE code, so an additional check isn't required.
