### ISSUE TITLE
Support use of meta-tab in spreadsheet uploads

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#52]
There is some interest in spreadsheet templates for OC4IDS (CRM-5838).

I tried loading a spreadsheet with a `Meta` tab to the Data Review Tool but it didn't work ([results](https://standard.open-contracting.org/infrastructure/review/data/3553284f-71fa-430b-bc5c-913edb65b9e3)).

Related issue where this feature was added to OCDS CoVE: https://github.com/OpenDataServices/cove/issues/641

**Comment by Bjwebb** [comment]
I think that PR probably makes this look more complicated than it is. That PR includes a bunch of refactoring, and things have changed since then.

I think the change would be to add some lines like https://github.com/open-contracting/cove-ocds/blob/d7a513ba69c5b478acf6a9e853ab170e5ecaac40/cove_ocds/views.py#L162-L179 to https://github.com/open-contracting/cove-oc4ids/blob/master/cove_oc4ids/views.py#L74

**Comment by jpmckinney** [comment]
Since OC4IDS has a single version and no extensions, I don't think a Meta tab is needed. Until we distribute spreadsheet templates with Meta tabs, users will not have such tabs in their uploaded files. So, closing for now.
