### ISSUE TITLE
Field level coverage: visualisation in browser

### ISSUE THREAD

**Issue by pindec** [open-contracting/cove-oc4ids#99]
Broad options: tree view vs list view

Pelican field level coverage provides:
- Both list and tree views, a search box to filter by field name, view toggles, and check filters (all/coverage failed only/quality failed only/passed only).
- List view is orderable by:
  -  field path asc/desc (default is field path asc) or 
  -  coverage asc/desc or
  - schema order
 
- Tree view is ordered by schema order only

Coverage data includes:
- % coverage
- raw numbers (count/total)
- progress bar to visualise % 

([front end](https://dqt.datlab.eu/field/180) | [source](https://github.com/open-contracting/pelican-frontend))

**Comment by pindec** [comment]
We also need to decide how to present this to users in the context of the existing DRT.

Given that this is a separate set of feedback to the structure and format check outlined in the current functionality, and takes up > 1 screen, we could create a new tab to show this to users, e.g.:

![image](https://user-images.githubusercontent.com/1897475/126983872-0dfb0690-3183-4cf4-960a-2de6ade67340.png)

We should use tooltips to indicate to users what the different tabs are for.
1. "Structure & format" - tooltip suggestion "Structure and format checks for your data"
2. "Field coverage" - tooltip suggestion "Field level coverage information for your data"

Suggested wording for the introduction section at the top of the "Field coverage" page:

"This field level coverage gives an overview of which fields are populated in your data. It is calculated using all core OC4IDS fields, excluding any additional fields and fields that are null or empty.  

If a field is on an object in an array, then field level coverage is reported for each object in the array. For example, in a data file with 100 projects, all of which have 5 `parties`, the field level coverage for the `parties` field will be calculated out of 100, but  field level coverage for its child fields (like `parties.id`) will be calculated out of 500.

Child fields are reported in the context of their parent field. For example, in a data file with 100 projects, 10 of which set `publicAuthority`,  field level coverage for the `publicAuthority` field will be calculated out of 100, but field level coverage for its child fields (like `publicAuthority.id`) will be calculated out of 10."

**Comment by jpmckinney** [comment]
The tabs should be clearly tabs (i.e. it should be clear which is the current tab, and that the other tabs are clickable).

cc @sabahfromlondon

**Comment by jpmckinney** [comment]
Noting that the suggested text is based on/close to Pelican's text, e.g. https://dqt.datlab.eu/field/302

**Comment by sabahfromlondon** [comment]
@jpmckinney what happens when there are no issues in one of the tab? Does the tab not appear? There could be some additional feedback to the user e.g. "Field coverage (2 issue  types)" or something like that?

**Comment by jpmckinney** [comment]
I think it's a good idea to include something like that. It's expected that there will always be missing field/indicator coverage, since no dataset has full coverage for every infrastructure project.

We might decide on a threshold for "low coverage" and report that on the field coverage tab. if we set the threshold at 0, then "Field coverage (20 missing)". If we set it at 10% or so, we can have a short, clear message (can't think of one now, unless we do something generic like "20 warnings").

For indicator coverage, if the threshold is 0, then I supposed "20 unsupported" as in the indicators are not supported by the dataset. If we use a higher threshold, then maybe "20 warnings" as before.

"Warnings" might be not bad, since we use the error/warning distinction on the implementation report to distinguish between issues that must be fixed and issues that might need to be fixed.

**Comment by pindec** [comment]
+1 for tabs that are obviously tabs with user feedback on where they are and what they can do. My example was to suggest text/position. 

re: text feedback for users in the title of the field level coverage tab - I think "warning" would be better than "missing" regardless of threshold, because of those cases where it's not possible to reduce the warnings to zero e.g. publishing a field is prohibited, so consistency with "issues that might need to be fixed" would be good. We should also add the definition of the warning and the threshold clear in the tab's intro text. 

Also noting that providing a user preview of the information in the tab presupposes that we will run the coverage checks at the time the user submits their OC4IDS data to the DRT, rather than on-demand once users click a tab. We don't anticipate issues with doing the former, but we'll need to confirm performance with some tests once the calculation mechanisms are in place.

We should also update the DRT submission page to flag the new functionality.

**Comment by pindec** [comment]
Can we please clarify some points so I can pass them on to the developers?:

1. **Suggested introductory text:** Is the [suggested introduction wording](#issuecomment-886649431) above OK?

2. **Field coverage tab - feedback for user - summary figure** - if it's helpful that users see a summary figure for their field level coverage on the tab, even if they can't action it (e.g. where they can't publish a field or where there is no completion information for projects that are not yet finished), then happy to add that info. 
Please confirm the threshold to be used to calculate the figure, the tab text, and the explanation to add to the field level introduction text to explain the summary figure.

3. **Updating the [DRT submission page](https://standard.open-contracting.org/infrastructure/review/)** - any thoughts? I think it makes sense to add a bullet to the bottom of the existing list in the "Check and review" box: 
![image](https://user-images.githubusercontent.com/1897475/127305832-ab69c341-dc0c-43c8-93f9-83e53497dbb5.png)
Draft text: "Explore your data's coverage of OC4IDS fields to identify possible additions".
-  We should also consider altering the line "Access your data in different formats (spreadsheet and JSON) to support further review." - given #78 (no flattening in DRT). 
- Data is still provided in JSON when submitting as a spreadsheet, so perhaps "Access your data in a different format (JSON) when checking flattened data (a CSV file or Excel Spreadsheet) to support further review"?
- For consistency, we should also update the sentence in the "Using the Data Review Tool box" that currently reads "It will also offer alternative copies of the data for download." to "If your data is in a flattened format (CSV file or Excel Spreadsheet), it will also offer a JSON copy of the data for download.

**Comment by pindec** [comment]
Some user feedback while demo-ing the Pelican field level coverage tree:
* re field coverage tab summary figure - the user wondered if there was an overall coverage figure, but also reported that during early implementation they fell into a trap of thinking that they should publish all OCDS fields, rather than focusing on user data needs, which meant there was a lack of vision beyond the standard.  They were pleased to see the coverage by section.

**Comment by pindec** [comment]
Noting that just doing the tree view visualisation is the priority for now (rather than replicating Pelican's list and tree view and a toggle between them).

**Comment by jpmckinney** [comment]
1. There are several issues with the first paragraph (missing noun in subject; it's not an overview - it has detail on every field; fields that are null or empty *are* included). Suggested fix: "This field-level coverage report details which OC4IDS fields are populated in your data."
2. I don't know what an appropriate threshold is. Since we don't know yet whether this will be expensive to pre-calculate, let's just omit this feature for now. (In future, we could have it asynchronously calculated if it's expensive.)
3. Bullet looks good.
4. Remove that bullet. It's not an especially relevant feature for what the DRT is designed to do.
5. Remove that sentence.

Until we can decide on a reasonable threshold, we can't add color. As discussed here and elsewhere, "good" is very context-dependent. I think a short bar is sufficient feedback, without the reinforcement of a color.

**Comment by pindec** [comment]
Great, thanks @jpmckinney, I think that is now everything agreed.

**Comment by kindly** [comment]
@jpmckinney @yolile 

I have been looking at tree view JavaScript libraries and js frameworks in order to complete this work.

As suggested in [the other thread](https://github.com/open-contracting/cove-oc4ids/issues/98#issuecomment-885771023) using [bootstrap collapasble/accordians](https://getbootstrap.com/docs/3.4/javascript/#collapse) is a possibility but would require a lot of very custom, potentially messy and time-consuming JQuery code to get the component to work as specified, especially adding the search box and filter in the specification.  
This is because there will require some kind of model for the search and filter requirements to, for example, make sure the parent fields are open if search result is found in a child.

Off the shelf libraries that do similar things include:

1. https://www.jstree.com/api/
2. https://github.com/mar10/fancytree
3. https://github.com/jonmiles/bootstrap-treeview
4. https://vuetifyjs.com/en/components/treeview/

The first 3 from my investigation lack either the theme customization, search or the ability to add the percentage bar and numbers.
Number 4 is flexible enough but it is a very heavyweight library (at least 0.5mb) to include for this purpose and I am not sure how easy it is to isolate the theme from the rest of the page.

My current feeling is that as custom JavaScript code is needed, it would be better written within a framework that was more suitable for this kind of work.
So I think vue/react/svelte/alpine makes sense here. However, I do not think we should rewrite the whole front-end in one of these by making it a single-page-app nor would we have time to do that [as commented](https://github.com/open-contracting/cove-oc4ids/issues/98#issuecomment-887587092)

Vue, for example, can be used just like a library and only work on a part of the page (e.g attached to any div) and can be imported from a CDN in the same way JQuery normally is.  

For example here is a fully self contained tree view example, written in vue by using this method.

https://codesandbox.io/s/github/vuejs/vuejs.org/tree/master/src/v2/examples/vue-20-tree-view?from-embed   

If done in this way it would be fairly easy to emulate the exact behavior of pelican by using some of the code/templates/theme from:

https://github.com/open-contracting/pelican-frontend/blob/main/frontend/src/components/FieldCheckTree.vue
https://github.com/open-contracting/pelican-frontend/blob/main/frontend/src/components/FieldCheckTreeNode.vue

Sadly I do not think any actual reuse of this code is possible as the underlying data models will be different and the components are fairly tied to that.

However, I think it would save time having pelican vue code to base this work off and hopefully some reuse opportunities could exist.

The downside of this approach is the extra vue js dependencies making the page slower to load.  However I think this will be insignificant compared the the processing time of the files themselves.

The other option is svelte which is very similar to vue but has a very small footprint, can be used in a non-SPA context, and has a similar example to vue:
https://svelte.dev/repl/a3f724e24df54b9695402576ffd68fe3?version=3.23.2
Also [AlpineJS](https://alpinejs.dev) is another popular lightweight option that would be preferable then custom jQuery.

However, as I have experience with vue and as it is also used in pelican, it is probably the most sensible choice.

So something custom in vue similar to pelican (but not a SPA or using .vue files) just for this component, is my preferred approach at the moment but would like some feedback on the approach before I go ahead.

**Comment by yolile** [comment]
It makes sense to me, my only worry is that maybe some libraries that Vue introduces could collide with the ones that CoVE already uses. 

> Vue, for example, can be used just like a library and only work on a part of the page (e.g attached to any div) and can be imported from a CDN in the same way JQuery normally is.

Maybe you can try this on a new, empty page, and see how many issues (if any) it has.

**Comment by kindly** [comment]
@yolile thanks.

I have tested out the vue  tree-view example on the explore page  (the page where the field coverage will be) and it does not conflict with anything in cove and works as expected.

**Comment by jpmckinney** [comment]
Thank you for the clear analysis of options. Using Vue sounds good to me.

**Comment by kindly** [comment]
@jpmckinney @yolile @duncandewhurst 

I have deployed a test instance on digital-ocean app platform (it was the quickest way for me to get something online) for feedback:

https://cove-oc-4-ids-o6dxs.ondigitalocean.app/

example data:

https://cove-oc-4-ids-o6dxs.ondigitalocean.app/infrastructure/review/data/22321ca4-3be3-4e22-b097-c0b46b700949

I think I have covered what is outlined in the spec, in doing so have tried to replicate the behavior of Pelican as much as possible including searching and filter behaviour.   There are differences in the theme and minor things like the tooltips on the field names.

Sadly reuse of the Pelican code was not really possible as the underlying model is different.  
Of note we have tried to keep the model as "augmented" JsonSchema with the origianal (dereffed) JsonSchema but with more fields and coverage information plus a few extras added by javascript to help drive the view eg. what parts of the tree are open.
This approach could be interesting if, for example, we want to make a version of docson that is searchable or more cusomisable, the underlying code would be very similar except for what parts of the schema we display.

Code is on https://github.com/open-contracting/cove-oc4ids/tree/coverage-test, but a pull request is not worth making yet till the underlying libaries are merged as well as spanish i18n.

**Comment by duncandewhurst** [comment]
Thanks, @kindly. Looking good!

Here's a couple of links to the results for some real data,  which I used to check what datasets with differing levels of coverage look like: [CoST West Lombok](https://cove-oc-4-ids-o6dxs.ondigitalocean.app/infrastructure/review/data/36ca4c5f-0a69-40b5-8ddd-bae97132bbb7), [CoST Ukraine](https://cove-oc-4-ids-o6dxs.ondigitalocean.app/infrastructure/review/data/b651f7da-8a95-480b-b766-7a663e8cd032).

I noticed a couple of points:

1. Left-align all the % values so that they are easier to scan. At the moment, they are right-aligned with the values in brackets:

![image](https://user-images.githubusercontent.com/19265814/129628882-d56830dc-01bb-474b-9461-788110a90cd0.png)

2. Align the 'coverage' column heading with either the % value, the values in brackets, or the bar. I don't mind which. At the moment it isn't aligned with any of them:

![image](https://user-images.githubusercontent.com/19265814/129629068-b31f74ab-2c45-492f-b587-feff92bfa7be.png)

3. Support expand/collapse for objects in search results. For example, when searching for identifier, I would expect to be able to expand `parties/identifier` to check the coverage of it's child properties:

![image](https://user-images.githubusercontent.com/19265814/129629557-b4b5aa84-1adf-4b29-ad19-fb0c4bab953c.png)

4. In the introductory text:
  *  Add code formatting to field paths
  * Replace 'field-level coverage' and 'field level coverage' with 'coverage'.

![image](https://user-images.githubusercontent.com/19265814/129630359-99e26062-9d7c-4bec-a71f-c8ad48d269ad.png)

6. Update the landing page per https://github.com/open-contracting/cove-oc4ids/issues/99#issuecomment-888214979 and https://github.com/open-contracting/cove-oc4ids/issues/99#issuecomment-888491087

**Comment by duncandewhurst** [comment]
> Here's a couple of links to the results for some real data, which I used to check what datasets with differing levels of coverage look like: [CoST West Lombok](https://cove-oc-4-ids-o6dxs.ondigitalocean.app/infrastructure/review/data/36ca4c5f-0a69-40b5-8ddd-bae97132bbb7), [CoST Ukraine](https://cove-oc-4-ids-o6dxs.ondigitalocean.app/infrastructure/review/data/b651f7da-8a95-480b-b766-7a663e8cd032).

Looks like those links didn't persist. Here are the links to the data I used: [CoST West Lombok](http://intras.fllajlombokbaratkab.or.id/storage/docs/oc4ids.json), [CoST Ukraine](https://portal.costukraine.org/data.json).

**Comment by duncandewhurst** [comment]
From @jpmckinney:

>  I would guess that, when users see “100%”  for an expandable section, they might not realize than children could be less than 100%, so there should be a note somewhere (not in the intro), to address that misinterpretation and encourage users to expand sections.

We agreed on:

![image](https://user-images.githubusercontent.com/19265814/129632628-91529869-eb2d-485d-9b6b-c0bf290131ef.png)

**Comment by yolile** [comment]
I tried with this [JSON from Nuevo Leon](http://si.nl.gob.mx/acceso/DatosAbiertos/DocumentosPublicos/000342/oc4ids-gx3fo2-000342-PRPv000003.json) and after a while, the site crashed. The current DRT was able to produce [results](https://standard.open-contracting.org/infrastructure/review/data/cd07b08b-4af7-4a7e-8dbd-54073c03d40f) though.

**Comment by kindly** [comment]
> I tried with this [JSON from Nuevo Leon](http://si.nl.gob.mx/acceso/DatosAbiertos/DocumentosPublicos/000342/oc4ids-gx3fo2-000342-PRPv000003.json) and after a while, the site crashed. The current DRT was able to produce [results](https://standard.open-contracting.org/infrastructure/review/data/cd07b08b-4af7-4a7e-8dbd-54073c03d40f) though.

This instance only has 512mb of RAM so was only really intended for a small demo of this feature.

**Comment by duncandewhurst** [comment]
That's interesting - it seemed to cope OK with the CoST Ukraine file with 12,000+ projects but no the Neuvo Leon one with one project.

**Comment by yolile** [comment]
It is looking good! The only extra thing that I can add to what was already said is that when you select "Coverage Failed Only" the % of some parent objects are missing, not sure if that is expected: 
![screenshot_4](https://user-images.githubusercontent.com/6834122/129637579-caff8521-6313-4667-8255-9c50e61c9d9c.png)

**Comment by kindly** [comment]
> The only extra thing that I can add to what was already said is that when you select "Coverage Failed Only" the % of some parent objects are missing, not sure if that is expected:

This was intentional.  When using "Coverage Failed Only" if an object is 100% coverage (but its children are not) then the bar/data is not show.

I am not sure what is more confusing, the current behavior, or showing 100% coverage for an object even with "Coverage Failed Only" is selected.

**Comment by kindly** [comment]
All the above comments have been looked into and the new version can be found in:

https://cove-oc-4-ids-o6dxs.ondigitalocean.app/

Pull request #104 is ready for review if there are no further changes required.

**Comment by duncandewhurst** [comment]
Thanks, @kindly. One minor point, otherwise the PR is ready for review:

Code formatting is missing on 'parties field' in the second paragraph of the introductory text:

![image](https://user-images.githubusercontent.com/19265814/129977832-ae46c770-25fd-42e9-871f-d9450688ed36.png)

> > The only extra thing that I can add to what was already said is that when you select "Coverage Failed Only" the % of some parent objects are missing, not sure if that is expected:
> 
> This was intentional. When using "Coverage Failed Only" if an object is 100% coverage (but its children are not) then the bar/data is not show.
> 
> I am not sure what is more confusing, the current behavior, or showing 100% coverage for an object even with "Coverage Failed Only" is selected.

I don't know which is best. The current behaviour is consistent with Pelican, so, unless anyone has a reason to prefer one over the other, let's stick with that.

**Comment by kindly** [comment]
@duncandewhurst this is done with a few more minor UI tweaks.

**Comment by duncandewhurst** [comment]
Looks good, thanks!

**Comment by duncandewhurst** [comment]
Done in https://github.com/open-contracting/cove-oc4ids/pull/104
